# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scraperequest_result_csv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
